### ISSUE TITLE
Missing tooltips and links to cadinfo pages

### ISSUE THREAD

**Issue by SmartFinn** [Monstrofil/kadastr.live#2]
Hello there,

The major feature of the service is unavailable. Probably due to a recent commit.
I would be glad if it is fixed as soon as possible.

Thanks.

**Comment by SmartFinn** [comment]
Oh, I see. Now the links appear on larger zoom than I'm used to.

**Comment by Monstrofil** [comment]
Hi,

I'm currently updating database with parcel geometry data, so portal may be working incorrectly. Hope all issues will be resolved till wednesday.

Let's keep this issue open for a while.

**Comment by Monstrofil** [comment]
It seems that all data is updated, also vector tiles are now available.

![image](https://user-images.githubusercontent.com/8678392/144744423-b90b0949-ef00-4563-89c0-f4e622acc4ba.png)

Sorry for delay, I had unexpected issues with data scraping.
